version: '3'

services:
  gslc-api:
    build: .
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./gsl_api:/app/gsl_api
      - ./output:/gsl-tmp-output/
